- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: gceme-backend
    namespace: production
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: gceme
          env: production
          role: backend
        name: backend
      spec:
        containers:
          - command:
              - sh
              - '-c'
              - app -port=8080
            image: gcr.io/vic-next-2018-demo/sample-app
            imagePullPolicy: Always
            name: backend
            ports:
              - containerPort: 8080
                name: backend
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8080
            resources:
              limits:
                cpu: 100m
                memory: 500Mi
- apiVersion: v1
  kind: Service
  metadata:
    name: gceme-backend
    namespace: production
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: gceme
      role: backend
