- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: gceme-frontend
    namespace: production
  spec:
    template:
      metadata:
        labels:
          app: gceme
          env: production
          role: frontend
        name: frontend
      spec:
        containers:
          - command:
              - sh
              - '-c'
              - >-
                app -frontend=true -backend-service=http://gceme-backend:8080
                -port=80
            image: gcr.io/vic-next-2018-demo/sample-app
            imagePullPolicy: Always
            name: frontend
            ports:
              - containerPort: 80
                name: frontend
            readinessProbe:
              httpGet:
                path: /healthz
                port: 80
            resources:
              limits:
                cpu: 100m
                memory: 500Mi
- apiVersion: v1
  kind: Service
  metadata:
    name: gceme-frontend
    namespace: production
  spec:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
    selector:
      app: gceme
      role: frontend
    type: LoadBalancer
